export const COURSES: Course[] = [
  {
    subject: "CS",
    catalogNbr: 1110,
    titleShort: "Intro Computing: Design & Dev",
  },
  {
    subject: "CS",
    catalogNbr: 1112,
    titleShort: "Intro Computing: Engrg & Sci",
  },
  { subject: "CS", catalogNbr: 1132, titleShort: "Short Course in MATLAB" },
  { subject: "CS", catalogNbr: 1133, titleShort: "Short Course in Python" },
  { subject: "CS", catalogNbr: 1340, titleShort: "Consequences in Computing" },
  { subject: "CS", catalogNbr: 1700, titleShort: "Elements of AI" },
  { subject: "CS", catalogNbr: 1998, titleShort: "First-year Team Projects" },
  { subject: "CS", catalogNbr: 2043, titleShort: "UNIX Tools and Scripting" },
  {
    subject: "CS",
    catalogNbr: 2110,
    titleShort: "Obj-Oriented Prog & Data Struc",
  },
  { subject: "CS", catalogNbr: 2800, titleShort: "Math Foundations of CS" },
  {
    subject: "CS",
    catalogNbr: 3110,
    titleShort: "Data Struct & Functional Progr",
  },
  { subject: "CS", catalogNbr: 3152, titleShort: "Intro Game Architecture" },
  {
    subject: "CS",
    catalogNbr: 3410,
    titleShort: "Computer System Organization",
  },
  { subject: "CS", catalogNbr: 3420, titleShort: "Embedded Systems" },
  {
    subject: "CS",
    catalogNbr: 3700,
    titleShort: "AI Reasoning/Decision-Making",
  },
  { subject: "CS", catalogNbr: 3780, titleShort: "Intro to Machine Learning" },
  { subject: "CS", catalogNbr: 4090, titleShort: "Teaching Experience in CS" },
  { subject: "CS", catalogNbr: 4152, titleShort: "Adv Game Architecture" },
  {
    subject: "CS",
    catalogNbr: 4220,
    titleShort: "Num Analysis: Lin&Nonlin Equat",
  },
  { subject: "CS", catalogNbr: 4300, titleShort: "Language and Information" },
  { subject: "CS", catalogNbr: 4410, titleShort: "Operating Systems" },
  { subject: "CS", catalogNbr: 4411, titleShort: "Practicum in Oper Syst" },
  { subject: "CS", catalogNbr: 4450, titleShort: "Intro to Computer Networks" },
  { subject: "CS", catalogNbr: 4670, titleShort: "Intro to Computer Vision" },
  { subject: "CS", catalogNbr: 4701, titleShort: "Prac in A I" },
  { subject: "CS", catalogNbr: 4740, titleShort: "Natural Lang Process" },
  {
    subject: "CS",
    catalogNbr: 4744,
    titleShort: "Computational Linguistics I",
  },
  { subject: "CS", catalogNbr: 4754, titleShort: "Re-Designing Robots" },
  { subject: "CS", catalogNbr: 4756, titleShort: "Robot Learning" },
  { subject: "CS", catalogNbr: 4758, titleShort: "Autonomous Mobile Robots" },
  {
    subject: "CS",
    catalogNbr: 4782,
    titleShort: "Introduction to Deep Learning",
  },
  {
    subject: "CS",
    catalogNbr: 4789,
    titleShort: "Intro Reinforcement Learning",
  },
  { subject: "CS", catalogNbr: 4810, titleShort: "Intro Theory Comp" },
  { subject: "CS", catalogNbr: 4813, titleShort: "Quantum Computing" },
  {
    subject: "CS",
    catalogNbr: 4820,
    titleShort: "Intro Analysis of Algorithms",
  },
  {
    subject: "CS",
    catalogNbr: 4850,
    titleShort: "Prob, Vectors, Matrices in CS",
  },
  { subject: "CS", catalogNbr: 4852, titleShort: "Networks II: Market Design" },
  {
    subject: "CS",
    catalogNbr: 4997,
    titleShort: "Practical Training in Comp Sci",
  },
  { subject: "CS", catalogNbr: 4998, titleShort: "Team Projects" },
  {
    subject: "CS",
    catalogNbr: 4999,
    titleShort: "Independent Reading & Research",
  },
  { subject: "ENGRI", catalogNbr: 1100, titleShort: "Laser & Photonics" },
  {
    subject: "ENGRI",
    catalogNbr: 1101,
    titleShort: "Engr Applications of ORIE",
  },
  { subject: "ENGRI", catalogNbr: 1130, titleShort: "Sustainable Engineering" },
  {
    subject: "ENGRI",
    catalogNbr: 1180,
    titleShort: "Building a Habitable Planet",
  },
  {
    subject: "CHEM",
    catalogNbr: 1008,
    titleShort: "Academic Support for CHEM 2080",
  },
  {
    subject: "CHEM",
    catalogNbr: 1058,
    titleShort: "Academic Support for CHEM 3580",
  },
  {
    subject: "CHEM",
    catalogNbr: 1570,
    titleShort: "Intro to Org and Bio Chemistry",
  },
  { subject: "CHEM", catalogNbr: 2070, titleShort: "General Chemistry I" },
  { subject: "CHEM", catalogNbr: 2080, titleShort: "General Chemistry II" },
  {
    subject: "CHEM",
    catalogNbr: 2090,
    titleShort: "Engineering General Chemistry",
  },
  { subject: "CHEM", catalogNbr: 2510, titleShort: "Intro Exper Organic Chem" },
  {
    subject: "CHEM",
    catalogNbr: 2780,
    titleShort: "Methods in Cheml Education II",
  },
  {
    subject: "CHEM",
    catalogNbr: 2900,
    titleShort: "Intro to Physical Chem Lab",
  },
  {
    subject: "CHEM",
    catalogNbr: 3010,
    titleShort: "Honors Experimental Chem I",
  },
  {
    subject: "CHEM",
    catalogNbr: 3030,
    titleShort: "Honors Experimental Chem III",
  },
  {
    subject: "CHEM",
    catalogNbr: 3570,
    titleShort: "Org Chem for Life Science",
  },
  {
    subject: "CHEM",
    catalogNbr: 3580,
    titleShort: "Org Chem For the Life Science",
  },
  { subject: "CHEM", catalogNbr: 3590, titleShort: "Honors Organic Chem I" },
  {
    subject: "CHEM",
    catalogNbr: 3880,
    titleShort: "Basics of Biophysical Chem",
  },
  { subject: "CHEM", catalogNbr: 3900, titleShort: "Honors Physical Chem II" },
  { subject: "CHEM", catalogNbr: 4100, titleShort: "Inorganic Chemistry" },
  { subject: "CHEM", catalogNbr: 4210, titleShort: "Intro Inorganic Research" },
  {
    subject: "CHEM",
    catalogNbr: 4330,
    titleShort: "Intro Analytical Research",
  },
  {
    subject: "CHEM",
    catalogNbr: 4430,
    titleShort: "Intro to Chem Bio Research",
  },
  { subject: "CHEM", catalogNbr: 4610, titleShort: "Intro Organic Research" },
  { subject: "CHEM", catalogNbr: 4770, titleShort: "Intro Physical Research" },
  {
    subject: "CHEM",
    catalogNbr: 4810,
    titleShort: "Computational Methods in Chemi",
  },
  { subject: "CHEM", catalogNbr: 4980, titleShort: "Honors Sem & Research" },
  { subject: "PHYS", catalogNbr: 1012, titleShort: "Physics 1112 Supplement" },
  { subject: "PHYS", catalogNbr: 1013, titleShort: "Physics 2213 Supplement" },
  { subject: "PHYS", catalogNbr: 1102, titleShort: "General Physics II" },
  {
    subject: "PHYS",
    catalogNbr: 1110,
    titleShort: "Intro. to Experimental Physics",
  },
  {
    subject: "PHYS",
    catalogNbr: 1112,
    titleShort: "Physics I: Mechanics & Heat",
  },
  {
    subject: "PHYS",
    catalogNbr: 1116,
    titleShort: "Phys I Mech & Spec Relativity",
  },
  {
    subject: "PHYS",
    catalogNbr: 1190,
    titleShort: "Intro Lab-Transfer Supplement",
  },
  {
    subject: "PHYS",
    catalogNbr: 1203,
    titleShort: "Physics of Heavens & Earth",
  },
  {
    subject: "PHYS",
    catalogNbr: 2208,
    titleShort: "Fundamentals of Physics II",
  },
  {
    subject: "PHYS",
    catalogNbr: 2210,
    titleShort: "Exploring Experimental Physics",
  },
  {
    subject: "PHYS",
    catalogNbr: 2213,
    titleShort: "Physics II: Electromagnetism",
  },
  {
    subject: "PHYS",
    catalogNbr: 2214,
    titleShort: "Phys III-Osc Waves & Quan Phys",
  },
  {
    subject: "PHYS",
    catalogNbr: 2216,
    titleShort: "Intro to Special Relativity",
  },
  { subject: "PHYS", catalogNbr: 2217, titleShort: "Phys II Elect&Magnetism" },
  {
    subject: "PHYS",
    catalogNbr: 2218,
    titleShort: "Phys III-Opt Waves&Therm Phys",
  },
  { subject: "PHYS", catalogNbr: 3310, titleShort: "Int Exp Phys" },
  {
    subject: "PHYS",
    catalogNbr: 3316,
    titleShort: "Basics of Quantum Mechanics",
  },
  { subject: "PHYS", catalogNbr: 3318, titleShort: "Analytical Mechanics" },
  { subject: "PHYS", catalogNbr: 3360, titleShort: "Electronic Circuits" },
  { subject: "PHYS", catalogNbr: 4400, titleShort: "Informal Adv Lab" },
  { subject: "PHYS", catalogNbr: 4410, titleShort: "Adv Experimental Physics" },
  {
    subject: "PHYS",
    catalogNbr: 4443,
    titleShort: "Intermed Quantum Mechanics",
  },
  { subject: "PHYS", catalogNbr: 4444, titleShort: "Intro to Particle Phys" },
  {
    subject: "PHYS",
    catalogNbr: 4484,
    titleShort: "Teaching and Learning Physics",
  },
  { subject: "PHYS", catalogNbr: 4485, titleShort: "Teaching Experience I" },
  { subject: "PHYS", catalogNbr: 4486, titleShort: "Teaching Experience II" },
  { subject: "PHYS", catalogNbr: 4487, titleShort: "Teaching Experience III" },
  { subject: "PHYS", catalogNbr: 4488, titleShort: "Statistical Mechanics" },
  {
    subject: "PHYS",
    catalogNbr: 4490,
    titleShort: "Independent Study in Physics",
  },
  { subject: "PHYS", catalogNbr: 4499, titleShort: "Senior Thesis II" },
  {
    subject: "PHYS",
    catalogNbr: 4688,
    titleShort: "Topics in Accelerator Physics",
  },
  {
    subject: "MATH",
    catalogNbr: 1006,
    titleShort: "Academic Support for Math 1106",
  },
  {
    subject: "MATH",
    catalogNbr: 1011,
    titleShort: "Academic Support for Math 1110",
  },
  {
    subject: "MATH",
    catalogNbr: 1012,
    titleShort: "Academic Support for Math 1120",
  },
  {
    subject: "MATH",
    catalogNbr: 1021,
    titleShort: "Academic Support for MATH 2210",
  },
  { subject: "MATH", catalogNbr: 1106, titleShort: "Modeling with Calculus" },
  { subject: "MATH", catalogNbr: 1110, titleShort: "Calculus I" },
  { subject: "MATH", catalogNbr: 1120, titleShort: "Calculus II" },
  {
    subject: "MATH",
    catalogNbr: 1340,
    titleShort: "Strategy, Cooperation&Conflict",
  },
  { subject: "MATH", catalogNbr: 1910, titleShort: "Calculus for Engineers" },
  {
    subject: "MATH",
    catalogNbr: 1920,
    titleShort: "Multivariable Calculus Engrs",
  },
  { subject: "MATH", catalogNbr: 2210, titleShort: "Linear Algebra" },
  { subject: "MATH", catalogNbr: 2220, titleShort: "Multivariable Calculus" },
  {
    subject: "MATH",
    catalogNbr: 2240,
    titleShort: "Theory:Linear Algebra/Calculus",
  },
  {
    subject: "MATH",
    catalogNbr: 2310,
    titleShort: "Linear Algebra for DataScience",
  },
  {
    subject: "MATH",
    catalogNbr: 2930,
    titleShort: "Differential Equations Engrs",
  },
  {
    subject: "MATH",
    catalogNbr: 2940,
    titleShort: "Linear Algebra for Engineers",
  },
  { subject: "MATH", catalogNbr: 3040, titleShort: "Prove It!" },
  { subject: "MATH", catalogNbr: 3110, titleShort: "Introduction to Analysis" },
  {
    subject: "MATH",
    catalogNbr: 3320,
    titleShort: "Introduction to Number Theory",
  },
  { subject: "MATH", catalogNbr: 3340, titleShort: "Abstract Algebra" },
  { subject: "MATH", catalogNbr: 3360, titleShort: "Applicable Algebra" },
  { subject: "MATH", catalogNbr: 4030, titleShort: "History of Mathematics" },
  { subject: "MATH", catalogNbr: 4130, titleShort: "Honors Intro Analysis I" },
  { subject: "MATH", catalogNbr: 4140, titleShort: "Honors Intro Analysis II" },
  { subject: "MATH", catalogNbr: 4180, titleShort: "Complex Analysis" },
  {
    subject: "MATH",
    catalogNbr: 4200,
    titleShort: "Diff Eqs & Dynamical Systems",
  },
  {
    subject: "MATH",
    catalogNbr: 4260,
    titleShort: "Num Analysis: Lin&Nonlin Equat",
  },
  {
    subject: "MATH",
    catalogNbr: 4280,
    titleShort: "Intro Partial Diff Equations",
  },
  { subject: "MATH", catalogNbr: 4310, titleShort: "Linear Algebra" },
  {
    subject: "MATH",
    catalogNbr: 4340,
    titleShort: "Honors Introduction to Algebra",
  },
  { subject: "MATH", catalogNbr: 4500, titleShort: "Matrix Groups" },
  {
    subject: "MATH",
    catalogNbr: 4540,
    titleShort: "Intro to Differential Geometry",
  },
  { subject: "MATH", catalogNbr: 4710, titleShort: "Basic Probability" },
  { subject: "MATH", catalogNbr: 4720, titleShort: "Statistics" },
  { subject: "MATH", catalogNbr: 4740, titleShort: "Stochastic Processes" },
  { subject: "MATH", catalogNbr: 4900, titleShort: "Supervised Research" },
  { subject: "MATH", catalogNbr: 4901, titleShort: "Supervised Reading" },
  {
    subject: "MATH",
    catalogNbr: 4980,
    titleShort: "Study for Mathematics Teaching",
  },
];
